version: 2.1

jobs:
    build:
        docker:
            - image: circleci/golang:1.12.5
            - image: circleci/mysql:8.0.16
              environment:
                  MYSQL_DATABASE: go_todo
        working_directory: /go/src/github.com/shoooooman/go-todolist-server
        steps:
            - checkout
            - run:
                name: get lib
                command: go get -v -t -d ./...
            - run:
                name: run server
                command: go run todo_server.go
                background: true
            - run:
                name: run test
                command: |
                    sleep 10
                    go test -v ./...
