version: 2.1

jobs:
    build:
        docker:
            - image: circleci/golang:1.12.5
        working_directory: /go/src/github.com/shoooooman/go-todolist-server
        steps:
            - checkout
            - run:
                name: get lib
                command: go get -d -t
            - run:
                name: run server
                command: go run todo_server.go
                backgroud: true
            - run:
                name: run test
                command: |
                    sleep 10
                    go test -v
